version: '3'
services:

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/mosquitto.passwd:/mosquitto/config/mosquitto.passwd
      - mosquitto:/mosquitto

volumes:
  mosquitto: {}
